package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * 
 * Auto-generated by spring-boot starter class
 *
 */
@SpringBootApplication
public class IvzelTestProjectForNullpointerApplication {

    public static void main(String[] args) {
        SpringApplication.run(IvzelTestProjectForNullpointerApplication.class, args);
    }
}
